import os
import config

def run_diagnostic():
    directories = {
        "Base Directory": config.BASE_DIR,
        "Dataset Directory": config.DATASET_DIR,
        "Models Directory": config.MODELS_DIR,
        "Outputs Directory": config.OUTPUTS_DIR
    }

    print("Verifying Core Directories:")
    for name, path in directories.items():
        status = "OK" if os.path.isdir(path) else "NOT FOUND (Will be auto-created)"
        print(f"  • {name:<20}: {path}")
        print(f"    Status: {status}")
    print()

    files = {
        "InsightFace Swapper Model": (config.SWAPPER_MODEL, True),
        "Custom Trained Classifier": (config.CLASSIFIER_MODEL, False),
        "Embeddings Registry Array": (config.EMBEDDINGS_REGISTRY, False),
        "Validation Metrics Log": (config.METRICS_LOG, False)
    }

    print("Verifying Critical System Files:")
    for name, (path, is_required_pre_run) in files.items():
        exists = os.path.isfile(path)

        if exists:
            status = "FOUND & READY"
        elif is_required_pre_run:
            status = "MISSING! (Action Required: You must download this file manually)"
        else:
            status = "NOT CREATED YET (Normal: This will be generated by the training pipeline)"

        print(f"  • {name:<25}: {path}")
        print(f"    Status: {status}")


if __name__ == "__main__":
    run_diagnostic()